apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: http://localhost:8081/repository/helm-base
      name: helm-base
      username: admin
      password: admin123
