apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: http://192.168.0.105:8081/repository/helm-base
      name: helm-base
      type: helm
      usernameSecret:
        name: nexus-helm-repo-creds
        key: username
      passwordSecret:
        name: nexus-helm-repo-creds
        key: password
