apiVersion: v1
kind: Secret
metadata:
  name: nexus-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: helm-base
  url: http://localhost:8081/repository/helm-base
  username: admin
  password: admin123
